---
title: yordex.com
timezone: Europe/London
collections:
  authors:
    title: Authors
    output: false
  posts:
    title: Posts
    output: true
  testimonials:
    title: Testimonials
    output: false
  topics:
    title: Topics
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    excerpt: 
    topic: 
    image: 
    author: 
- scope:
    path: ''
    type: topics
  values:
    permalink: "/category/:title/"
    layout: category
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: testimonials
  values:
    author:
      name: 
      title: 
      company: 
      profile-image: 
    logo-image: 
    color: 
url: http://blog.yordex.com
description: Simplify your payment process with our software to automate the accounts
  payable system for both buyers and sellers. Reduce cost and improve payment terms.
twitter:
  username: YordexLTD
social:
  links:
  - name: Twitter
    link: https://www.twitter.com/YordexLTD
  - name: LinkedIn
    link: https://www.linkedin.com/company/yordex
footer_text: Procure-to-pay platform to save time, increase visibility into spend
  and improve cash flow.
date_format: "%-d %B %Y"
per_page: 10
gtm-code: GTM-55TB3WF
excerpt_separator: |2+
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
